### ISSUE TITLE
Cannot login / cannot run entrypoint.sh init

### ISSUE THREAD

**Issue by csakoda** [groventure/docker-ratticdb-uwsgi#1]
I got the service up, but cannot login as there's no users.  Trying to get demosetup run produces the following errors

```
root@551f0b5b9197:/srv/rattic# bash /scripts/entrypoint.sh init
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/dist-packages/south/management/commands/syncdb.py", line 68, in handle_noargs
    migrations = migration.Migrations(app_label)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 64, in __call__
    self.instances[app_label] = super(MigrationsMetaclass, self).__call__(app_label_to_app_module(app_label), **kwds)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 90, in __init__
    self.set_application(application, force_creation, verbose_creation)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 154, in set_application
    module = importlib.import_module(self.migrations_module())
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/django/migrations/__init__.py", line 16, in <module>
    raise ImproperlyConfigured(SOUTH_ERROR_MESSAGE)
django.core.exceptions.ImproperlyConfigured:
For South support, customize the SOUTH_MIGRATION_MODULES setting
to point to the correct migrations module:

    SOUTH_MIGRATION_MODULES = {
        'kombu_transport_django': 'kombu.transport.django.south_migrations',
    }
```

**Comment by gvithellyna** [comment]
Not sure what's wrong. I have tried adding SOUTH_MIGRATION_MODULES block mentioned in the stacktrace to ratticweb/settings.py and it doesn't work. I am not a Django Developer too so I am not sure what is happening. The same error occurs after that.

**Comment by gvithellyna** [comment]
Existing containers shouldn't be affected though. This seems to break after a specific release version of "something". Probably its(ratticdb) dependencies from pip somehow caused this error.

Just in case: do you have any idea?

**Comment by csakoda** [comment]
Yeah, I figured it out.

It seems `django-celery` >= 3.1.17 and `kombu` >= 3.0.28 both expect to be running with django 1.7, which uses the newer migration model that conflicts with South.  Fixing those packages to less than the specified versions seems to resolve it. 

I did this here: https://github.com/csakoda/RatticWeb

We should probably just close this since the problem is not with your repo.

**Comment by csakoda** [comment]
This pull should resolve it in the upstream repo: https://github.com/tildaslash/RatticWeb/pull/406

**Comment by gvithellyna** [comment]
Thanks @csakoda :)
